### ISSUE TITLE
Get MapboxGL Hash back

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-streets#38]
For consistency across apps, we want the mapboxGL native location hash back in the app.

**Comment by allthesignals** [comment]
In practice and principle, I disagree with using the _hash_ for storing state for applications that include other map-related state. Re-introducing hash into this app means we manage state in the URL in two difference formats: 1) query parameters (which is a standard part of REST to communicate application state) and 2) the browser Location API, which natively just adjust the scroll position on the window. 

Currently, this app references in the hash in two places, both of which must be recomputed as they aren't implemented as event-based actions:
1) `mapLatLngZoomHash` is used in the "view this in ZoLa" feature
2) `shareURL` is used in the share button.

Computed properties can't reference globals, like `window`, which aren't future-proof (nor cross-browser safe), as we may introduce server-side rendering at some point, so we would need to switch to using event-based actions to evaluate the URL at the time of the click. This will only work for the feature #1 because #2 previews the share link in actual markup. One requires a computed property based on application state, one doesn't, meaning we would be taking two approaches simultaneously for the dealing with the exact same data. Additionally, we would need to track latitude, longitude, and zoom state _anyways_ because it would be needed for re-computing the value for the share link (which again is previewed in markup and needs to update with data). All of this to say that using the hash, a different format, when we already have query params (it is _not_ that painful to create a hash-based link referencing those values separately). If pitch and bearing in the hash are so crucial, they can be created too.

**Comment by chriswhong** [comment]
My arguments _for_ using the hash are as follows:
- It's a free feature in mapboxGL
- It's consistent with any other webmap we make using mapboxGL (meaning we can make simple, non-ember, plain old web sites and still make use of the hash to build a view)

I think if we have the ability to work around it in our framework/ apps, we should.  MpaboxGL gives us lots of convenient events to tap into when any of the view parameters change, so it should not be too difficult to get the values from the map object and use them wherever we need them.

**Comment by allthesignals** [comment]
> It's a free feature in mapboxGL

So are query params. It is also not a totally free feature as that is data we need to use it other parts of the application. It is free for a limited use case, but anything beyond that, it begins to cost (which it is right now, in the 2 features I pointed out).

> It's consistent with any other webmap we make using mapboxGL (meaning we can make simple, non-ember, plain old web sites and still make use of the hash to build a view)

This is a matter of:
`return '#${zoom}/${lng}/${lat}';`

But you're right, MapboxGL does give us convenient events, like the `move` event, which we can use to update state inside traditional query params.

**Comment by jpiacentinidcp** [comment]
no longer relevant
